name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: The version (x.y.z) for this release
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: x86_64-unknown-linux-musl
          override: true

      - run: sed -i 's/^version = "0.0.0"$/version = "${{ github.event.inputs.version }}"/' Cargo.toml

      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target x86_64-unknown-linux-gnu --release

      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target aarch64-unknown-linux-gnu --release

      - run: mv target/x86_64-unknown-linux-gnu/release/reload reload_x86_64-unknown-linux-gnu
      - run: mv target/aarch64-unknown-linux-gnu/release/reload reload_aarch64-unknown-linux-gnu

      - uses: softprops/action-gh-release@v1
        with:
          name: ${{ github.event.inputs.version }}
          tag_name: ${{ github.event.inputs.version }}
          files: |
            reload_x86_64-unknown-linux-gnu
            reload_aarch64-unknown-linux-gnu
            LICENSE
            readme.md
